/* --- Generated the 11/11/2019 at 8:47 --- */
/* --- heptagon compiler, version 1.03.00 (compiled thu. may. 3 2:35:29 CET 2018) --- */
/* --- Command line: /usr/local/bin/heptc -target c instanciador_controller.ept --- */

#ifndef INSTANCIADOR_CONTROLLER_H
#define INSTANCIADOR_CONTROLLER_H

#include "instanciador_controller_types.h"
typedef struct Instanciador_controller__instanciador_controller_instanciador_ca_out {
  int instanciador_ca;
} Instanciador_controller__instanciador_controller_instanciador_ca_out;

void Instanciador_controller__instanciador_controller_instanciador_ca_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_alarm, int instanciador_cg, int instanciador_c_gela,
int instanciador_cp, int instanciador_c_proj, int instanciador_cmp,
int instanciador_c_microP, int instanciador_cml, int instanciador_c_microL,
int instanciador_csl, int instanciador_c_somL, int instanciador_csp,
int instanciador_c_somP, int instanciador_c_vent, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_ca_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_alarm_out {
  int instanciador_c_alarm;
} Instanciador_controller__instanciador_controller_instanciador_c_alarm_out;

void Instanciador_controller__instanciador_controller_instanciador_c_alarm_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cg,
int instanciador_c_gela, int instanciador_cp, int instanciador_c_proj,
int instanciador_cmp, int instanciador_c_microP, int instanciador_cml,
int instanciador_c_microL, int instanciador_csl, int instanciador_c_somL,
int instanciador_csp, int instanciador_c_somP, int instanciador_c_vent,
int instanciador_cv, int instanciador_cx, int instanciador_c4,
int instanciador_c3, int instanciador_c2, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_alarm_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cg_out {
  int instanciador_cg;
} Instanciador_controller__instanciador_controller_instanciador_cg_out;

void Instanciador_controller__instanciador_controller_instanciador_cg_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_gela, int instanciador_cp, int instanciador_c_proj,
int instanciador_cmp, int instanciador_c_microP, int instanciador_cml,
int instanciador_c_microL, int instanciador_csl, int instanciador_c_somL,
int instanciador_csp, int instanciador_c_somP, int instanciador_c_vent,
int instanciador_cv, int instanciador_cx, int instanciador_c4,
int instanciador_c3, int instanciador_c2, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cg_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_gela_out {
  int instanciador_c_gela;
} Instanciador_controller__instanciador_controller_instanciador_c_gela_out;

void Instanciador_controller__instanciador_controller_instanciador_c_gela_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cp,
int instanciador_c_proj, int instanciador_cmp, int instanciador_c_microP,
int instanciador_cml, int instanciador_c_microL, int instanciador_csl,
int instanciador_c_somL, int instanciador_csp, int instanciador_c_somP,
int instanciador_c_vent, int instanciador_cv, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_gela_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cp_out {
  int instanciador_cp;
} Instanciador_controller__instanciador_controller_instanciador_cp_out;

void Instanciador_controller__instanciador_controller_instanciador_cp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_proj, int instanciador_cmp, int instanciador_c_microP,
int instanciador_cml, int instanciador_c_microL, int instanciador_csl,
int instanciador_c_somL, int instanciador_csp, int instanciador_c_somP,
int instanciador_c_vent, int instanciador_cv, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_proj_out {
  int instanciador_c_proj;
} Instanciador_controller__instanciador_controller_instanciador_c_proj_out;

void Instanciador_controller__instanciador_controller_instanciador_c_proj_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cmp,
int instanciador_c_microP, int instanciador_cml, int instanciador_c_microL,
int instanciador_csl, int instanciador_c_somL, int instanciador_csp,
int instanciador_c_somP, int instanciador_c_vent, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_proj_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cmp_out {
  int instanciador_cmp;
} Instanciador_controller__instanciador_controller_instanciador_cmp_out;

void Instanciador_controller__instanciador_controller_instanciador_cmp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_microP, int instanciador_cml, int instanciador_c_microL,
int instanciador_csl, int instanciador_c_somL, int instanciador_csp,
int instanciador_c_somP, int instanciador_c_vent, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cmp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_microP_out {
  int instanciador_c_microP;
} Instanciador_controller__instanciador_controller_instanciador_c_microP_out;

void Instanciador_controller__instanciador_controller_instanciador_c_microP_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cml,
int instanciador_c_microL, int instanciador_csl, int instanciador_c_somL,
int instanciador_csp, int instanciador_c_somP, int instanciador_c_vent,
int instanciador_cv, int instanciador_cx, int instanciador_c4,
int instanciador_c3, int instanciador_c2, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_microP_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cml_out {
  int instanciador_cml;
} Instanciador_controller__instanciador_controller_instanciador_cml_out;

void Instanciador_controller__instanciador_controller_instanciador_cml_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_microL, int instanciador_csl, int instanciador_c_somL,
int instanciador_csp, int instanciador_c_somP, int instanciador_c_vent,
int instanciador_cv, int instanciador_cx, int instanciador_c4,
int instanciador_c3, int instanciador_c2, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cml_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_microL_out {
  int instanciador_c_microL;
} Instanciador_controller__instanciador_controller_instanciador_c_microL_out;

void Instanciador_controller__instanciador_controller_instanciador_c_microL_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_csl,
int instanciador_c_somL, int instanciador_csp, int instanciador_c_somP,
int instanciador_c_vent, int instanciador_cv, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_microL_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_csl_out {
  int instanciador_csl;
} Instanciador_controller__instanciador_controller_instanciador_csl_out;

void Instanciador_controller__instanciador_controller_instanciador_csl_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_somL, int instanciador_csp, int instanciador_c_somP,
int instanciador_c_vent, int instanciador_cv, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_csl_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_somL_out {
  int instanciador_c_somL;
} Instanciador_controller__instanciador_controller_instanciador_c_somL_out;

void Instanciador_controller__instanciador_controller_instanciador_c_somL_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_csp,
int instanciador_c_somP, int instanciador_c_vent, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_somL_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_csp_out {
  int instanciador_csp;
} Instanciador_controller__instanciador_controller_instanciador_csp_out;

void Instanciador_controller__instanciador_controller_instanciador_csp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_somP, int instanciador_c_vent, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_csp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_somP_out {
  int instanciador_c_somP;
} Instanciador_controller__instanciador_controller_instanciador_c_somP_out;

void Instanciador_controller__instanciador_controller_instanciador_c_somP_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_vent, int instanciador_cv, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_somP_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_vent_out {
  int instanciador_c_vent;
} Instanciador_controller__instanciador_controller_instanciador_c_vent_out;

void Instanciador_controller__instanciador_controller_instanciador_c_vent_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cv,
int instanciador_cx, int instanciador_c4, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_vent_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cv_out {
  int instanciador_cv;
} Instanciador_controller__instanciador_controller_instanciador_cv_out;

void Instanciador_controller__instanciador_controller_instanciador_cv_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_cx,
int instanciador_c4, int instanciador_c3, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cv_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_cx_out {
  int instanciador_cx;
} Instanciador_controller__instanciador_controller_instanciador_cx_out;

void Instanciador_controller__instanciador_controller_instanciador_cx_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_c4,
int instanciador_c3, int instanciador_c2, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_cx_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c4_out {
  int instanciador_c4;
} Instanciador_controller__instanciador_controller_instanciador_c4_out;

void Instanciador_controller__instanciador_controller_instanciador_c4_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_c3,
int instanciador_c2, int instanciador_c1, int instanciador_c_lampExt,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c4_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c3_out {
  int instanciador_c3;
} Instanciador_controller__instanciador_controller_instanciador_c3_out;

void Instanciador_controller__instanciador_controller_instanciador_c3_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_c2,
int instanciador_c1, int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c3_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c2_out {
  int instanciador_c2;
} Instanciador_controller__instanciador_controller_instanciador_c2_out;

void Instanciador_controller__instanciador_controller_instanciador_c2_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp, int instanciador_c1,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c2_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c1_out {
  int instanciador_c1;
} Instanciador_controller__instanciador_controller_instanciador_c1_out;

void Instanciador_controller__instanciador_controller_instanciador_c1_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c_lampExt, int instanciador_c4_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c1_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c_lampExt_out {
  int instanciador_c_lampExt;
} Instanciador_controller__instanciador_controller_instanciador_c_lampExt_out;

void Instanciador_controller__instanciador_controller_instanciador_c_lampExt_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c4_lamp, int instanciador_c3_lamp, int instanciador_c2_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c_lampExt_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c4_lamp_out {
  int instanciador_c4_lamp;
} Instanciador_controller__instanciador_controller_instanciador_c4_lamp_out;

void Instanciador_controller__instanciador_controller_instanciador_c4_lamp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c3_lamp, int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c4_lamp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c3_lamp_out {
  int instanciador_c3_lamp;
} Instanciador_controller__instanciador_controller_instanciador_c3_lamp_out;

void Instanciador_controller__instanciador_controller_instanciador_c3_lamp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c2_lamp, int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c3_lamp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c2_lamp_out {
  int instanciador_c2_lamp;
} Instanciador_controller__instanciador_controller_instanciador_c2_lamp_out;

void Instanciador_controller__instanciador_controller_instanciador_c2_lamp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
int instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c2_lamp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_instanciador_c1_lamp_out {
  int instanciador_c1_lamp;
} Instanciador_controller__instanciador_controller_instanciador_c1_lamp_out;

void Instanciador_controller__instanciador_controller_instanciador_c1_lamp_step(
int instanciador_sexta_input, int instanciador_ebd_input,
int instanciador_domingo_input, int instanciador_domingol_input,
int instanciador_neutro_input, int instanciador_seguranca_input,
int instanciador_l1, int instanciador_l2, int instanciador_l3,
int instanciador_l4, int instanciador_lx, int instanciador_lv,
int instanciador_inpMl, int instanciador_inpMp, int instanciador_inpSp,
int instanciador_inpSl, int instanciador_inpProj, int instanciador_inpGela,
int instanciador_inpAlarm, int instanciador_v_341, int instanciador_v_340,
int instanciador_v_339, int instanciador_pnr_13, int instanciador_ck_9_1,
int instanciador_pnr_12, int instanciador_ck_11_1, int instanciador_pnr_11,
int instanciador_ck_13_1, int instanciador_pnr_10, int instanciador_ck_15_1,
int instanciador_pnr_9, int instanciador_ck_17_1, int instanciador_pnr_8,
int instanciador_ck_19_1, int instanciador_pnr_7, int instanciador_ck_21_1,
int instanciador_pnr_6, int instanciador_ck_23_1, int instanciador_pnr_5,
int instanciador_ck_25_1, int instanciador_pnr_4, int instanciador_ck_27_1,
int instanciador_pnr_3, int instanciador_ck_29_1, int instanciador_pnr_2,
int instanciador_ck_31_1, int instanciador_pnr_1, int instanciador_ck_33_1,
int instanciador_pnr, int p_instanciador_ca, int p_instanciador_c_alarm,
int p_instanciador_cg, int p_instanciador_c_gela, int p_instanciador_cp,
int p_instanciador_c_proj, int p_instanciador_cmp,
int p_instanciador_c_microP, int p_instanciador_cml,
int p_instanciador_c_microL, int p_instanciador_csl,
int p_instanciador_c_somL, int p_instanciador_csp, int p_instanciador_c_somP,
int p_instanciador_c_vent, int p_instanciador_cv, int p_instanciador_cx,
int p_instanciador_c4, int p_instanciador_c3, int p_instanciador_c2,
int p_instanciador_c1, int p_instanciador_c_lampExt,
int p_instanciador_c4_lamp, int p_instanciador_c3_lamp,
int p_instanciador_c2_lamp, int p_instanciador_c1_lamp,
Instanciador_controller__instanciador_controller_instanciador_c1_lamp_out* _out);

typedef struct Instanciador_controller__instanciador_controller_out {
  int instanciador_ca;
  int instanciador_c_alarm;
  int instanciador_cg;
  int instanciador_c_gela;
  int instanciador_cp;
  int instanciador_c_proj;
  int instanciador_cmp;
  int instanciador_c_microP;
  int instanciador_cml;
  int instanciador_c_microL;
  int instanciador_csl;
  int instanciador_c_somL;
  int instanciador_csp;
  int instanciador_c_somP;
  int instanciador_c_vent;
  int instanciador_cv;
  int instanciador_cx;
  int instanciador_c4;
  int instanciador_c3;
  int instanciador_c2;
  int instanciador_c1;
  int instanciador_c_lampExt;
  int instanciador_c4_lamp;
  int instanciador_c3_lamp;
  int instanciador_c2_lamp;
  int instanciador_c1_lamp;
} Instanciador_controller__instanciador_controller_out;

void Instanciador_controller__instanciador_controller_step(int instanciador_sexta_input,
                                                           int instanciador_ebd_input,
                                                           int instanciador_domingo_input,
                                                           int instanciador_domingol_input,
                                                           int instanciador_neutro_input,
                                                           int instanciador_seguranca_input,
                                                           int instanciador_l1,
                                                           int instanciador_l2,
                                                           int instanciador_l3,
                                                           int instanciador_l4,
                                                           int instanciador_lx,
                                                           int instanciador_lv,
                                                           int instanciador_inpMl,
                                                           int instanciador_inpMp,
                                                           int instanciador_inpSp,
                                                           int instanciador_inpSl,
                                                           int instanciador_inpProj,
                                                           int instanciador_inpGela,
                                                           int instanciador_inpAlarm,
                                                           int instanciador_v_341,
                                                           int instanciador_v_340,
                                                           int instanciador_v_339,
                                                           int instanciador_pnr_13,
                                                           int instanciador_ck_9_1,
                                                           int instanciador_pnr_12,
                                                           int instanciador_ck_11_1,
                                                           int instanciador_pnr_11,
                                                           int instanciador_ck_13_1,
                                                           int instanciador_pnr_10,
                                                           int instanciador_ck_15_1,
                                                           int instanciador_pnr_9,
                                                           int instanciador_ck_17_1,
                                                           int instanciador_pnr_8,
                                                           int instanciador_ck_19_1,
                                                           int instanciador_pnr_7,
                                                           int instanciador_ck_21_1,
                                                           int instanciador_pnr_6,
                                                           int instanciador_ck_23_1,
                                                           int instanciador_pnr_5,
                                                           int instanciador_ck_25_1,
                                                           int instanciador_pnr_4,
                                                           int instanciador_ck_27_1,
                                                           int instanciador_pnr_3,
                                                           int instanciador_ck_29_1,
                                                           int instanciador_pnr_2,
                                                           int instanciador_ck_31_1,
                                                           int instanciador_pnr_1,
                                                           int instanciador_ck_33_1,
                                                           int instanciador_pnr,
                                                           int p_instanciador_ca,
                                                           int p_instanciador_c_alarm,
                                                           int p_instanciador_cg,
                                                           int p_instanciador_c_gela,
                                                           int p_instanciador_cp,
                                                           int p_instanciador_c_proj,
                                                           int p_instanciador_cmp,
                                                           int p_instanciador_c_microP,
                                                           int p_instanciador_cml,
                                                           int p_instanciador_c_microL,
                                                           int p_instanciador_csl,
                                                           int p_instanciador_c_somL,
                                                           int p_instanciador_csp,
                                                           int p_instanciador_c_somP,
                                                           int p_instanciador_c_vent,
                                                           int p_instanciador_cv,
                                                           int p_instanciador_cx,
                                                           int p_instanciador_c4,
                                                           int p_instanciador_c3,
                                                           int p_instanciador_c2,
                                                           int p_instanciador_c1,
                                                           int p_instanciador_c_lampExt,
                                                           int p_instanciador_c4_lamp,
                                                           int p_instanciador_c3_lamp,
                                                           int p_instanciador_c2_lamp,
                                                           int p_instanciador_c1_lamp,
                                                           Instanciador_controller__instanciador_controller_out* _out);

#endif // INSTANCIADOR_CONTROLLER_H
